/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Urbanovic
 */
public class MainGUI extends javax.swing.JFrame {

    Session session = HibernateUtil.createSessionFactory().openSession();
    Transaction tx = null;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterButtonGroup = new javax.swing.ButtonGroup();
        newEmployeeDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newNameValue = new javax.swing.JTextField();
        newAgeValue = new javax.swing.JTextField();
        newAddressValue = new javax.swing.JTextField();
        newSalaryValue = new javax.swing.JTextField();
        newDialogSaveButton = new javax.swing.JButton();
        newDialogCancelButton = new javax.swing.JButton();
        editEmployeeDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editIDValue = new javax.swing.JTextField();
        editNameValue = new javax.swing.JTextField();
        editAgeValue = new javax.swing.JTextField();
        editAddressValue = new javax.swing.JTextField();
        editSalaryValue = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editDialogButton = new javax.swing.JButton();
        editDialogCancelButton = new javax.swing.JButton();
        deleteEmployeeDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        deleteIDValue = new javax.swing.JTextField();
        deleteDialogButton = new javax.swing.JButton();
        deleteDialogCancelButton = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        filterPanel = new javax.swing.JPanel();
        allEmployeesButton = new javax.swing.JRadioButton();
        olderThanButton = new javax.swing.JRadioButton();
        olderThanValue = new javax.swing.JTextField();
        youngerThanButton = new javax.swing.JRadioButton();
        youngerThanValue = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        salaryHigherButton = new javax.swing.JRadioButton();
        salaryLowerButton = new javax.swing.JRadioButton();
        salaryHigherValue = new javax.swing.JTextField();
        salaryLowerValue = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();

        newEmployeeDialog.setModal(true);
        newEmployeeDialog.setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New employee"));

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jLabel3.setText("Address");

        jLabel4.setText("Salary");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newAgeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newSalaryValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newAddressValue, newAgeValue, newNameValue, newSalaryValue});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newAgeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newSalaryValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newDialogSaveButton.setText("Save");
        newDialogSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDialogSaveButtonActionPerformed(evt);
            }
        });

        newDialogCancelButton.setText("Cancel");
        newDialogCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDialogCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newEmployeeDialogLayout = new javax.swing.GroupLayout(newEmployeeDialog.getContentPane());
        newEmployeeDialog.getContentPane().setLayout(newEmployeeDialogLayout);
        newEmployeeDialogLayout.setHorizontalGroup(
            newEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEmployeeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newEmployeeDialogLayout.createSequentialGroup()
                        .addComponent(newDialogSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newDialogCancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newEmployeeDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newDialogCancelButton, newDialogSaveButton});

        newEmployeeDialogLayout.setVerticalGroup(
            newEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newEmployeeDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDialogSaveButton)
                    .addComponent(newDialogCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editEmployeeDialog.setModal(true);
        editEmployeeDialog.setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit employee"));

        jLabel5.setText("Employee ID:");

        jLabel6.setText("Name:");

        jLabel7.setText("Age:");

        jLabel8.setText("Address:");

        jLabel9.setText("Salary:");

        jLabel10.setText("Empty fields will keep previous value.");

        jLabel11.setText("Must not be null!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAgeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editSalaryValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editAddressValue, editAgeValue, editIDValue, editNameValue, editSalaryValue});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(editNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(editAgeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(editAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(editSalaryValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        editDialogButton.setText("Edit");
        editDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDialogButtonActionPerformed(evt);
            }
        });

        editDialogCancelButton.setText("Cancel");
        editDialogCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDialogCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editEmployeeDialogLayout = new javax.swing.GroupLayout(editEmployeeDialog.getContentPane());
        editEmployeeDialog.getContentPane().setLayout(editEmployeeDialogLayout);
        editEmployeeDialogLayout.setHorizontalGroup(
            editEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmployeeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editEmployeeDialogLayout.createSequentialGroup()
                        .addComponent(editDialogButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editDialogCancelButton)))
                .addContainerGap())
        );

        editEmployeeDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editDialogButton, editDialogCancelButton});

        editEmployeeDialogLayout.setVerticalGroup(
            editEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmployeeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDialogButton)
                    .addComponent(editDialogCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteEmployeeDialog.setModal(true);
        deleteEmployeeDialog.setUndecorated(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete employee"));

        jLabel12.setText("Enter employee ID you wish to delete:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(deleteIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteIDValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteDialogButton.setText("Delete");
        deleteDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDialogButtonActionPerformed(evt);
            }
        });

        deleteDialogCancelButton.setText("Cancel");
        deleteDialogCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDialogCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteEmployeeDialogLayout = new javax.swing.GroupLayout(deleteEmployeeDialog.getContentPane());
        deleteEmployeeDialog.getContentPane().setLayout(deleteEmployeeDialogLayout);
        deleteEmployeeDialogLayout.setHorizontalGroup(
            deleteEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployeeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deleteEmployeeDialogLayout.createSequentialGroup()
                        .addComponent(deleteDialogButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteDialogCancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteEmployeeDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteDialogButton, deleteDialogCancelButton});

        deleteEmployeeDialogLayout.setVerticalGroup(
            deleteEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployeeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteEmployeeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteDialogButton)
                    .addComponent(deleteDialogCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        editPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit employees"));

        newButton.setText("New employee");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit employee");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete employee");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, editButton, newButton});

        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter display"));

        filterButtonGroup.add(allEmployeesButton);
        allEmployeesButton.setSelected(true);
        allEmployeesButton.setText("All employees");
        allEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allEmployeesButtonActionPerformed(evt);
            }
        });

        filterButtonGroup.add(olderThanButton);
        olderThanButton.setText("Older than");
        olderThanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olderThanButtonActionPerformed(evt);
            }
        });

        olderThanValue.setEnabled(false);

        filterButtonGroup.add(youngerThanButton);
        youngerThanButton.setText("Younger than");
        youngerThanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youngerThanButtonActionPerformed(evt);
            }
        });

        youngerThanValue.setEnabled(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        filterButtonGroup.add(salaryHigherButton);
        salaryHigherButton.setText("Salary higher than");
        salaryHigherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryHigherButtonActionPerformed(evt);
            }
        });

        filterButtonGroup.add(salaryLowerButton);
        salaryLowerButton.setText("Salary lower than");
        salaryLowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryLowerButtonActionPerformed(evt);
            }
        });

        salaryHigherValue.setEnabled(false);

        salaryLowerValue.setEnabled(false);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(youngerThanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allEmployeesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(olderThanButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(olderThanValue)
                    .addComponent(youngerThanValue, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salaryHigherButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salaryLowerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salaryHigherValue)
                            .addComponent(salaryLowerValue, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                    .addComponent(refreshButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {allEmployeesButton, olderThanButton, salaryHigherButton, salaryLowerButton, youngerThanButton});

        filterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {olderThanValue, salaryHigherValue, salaryLowerValue, youngerThanValue});

        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaryHigherButton)
                            .addComponent(salaryHigherValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaryLowerButton)
                            .addComponent(salaryLowerValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(filterPanelLayout.createSequentialGroup()
                                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(youngerThanValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(filterPanelLayout.createSequentialGroup()
                                        .addComponent(allEmployeesButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(olderThanButton)
                                            .addComponent(olderThanValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(youngerThanButton)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "Age", "Address", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeTable);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(0).setMinWidth(30);
            employeeTable.getColumnModel().getColumn(0).setPreferredWidth(75);
            employeeTable.getColumnModel().getColumn(0).setMaxWidth(100);
            employeeTable.getColumnModel().getColumn(1).setMinWidth(70);
            employeeTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            employeeTable.getColumnModel().getColumn(1).setMaxWidth(200);
            employeeTable.getColumnModel().getColumn(2).setMinWidth(20);
            employeeTable.getColumnModel().getColumn(2).setPreferredWidth(35);
            employeeTable.getColumnModel().getColumn(2).setMaxWidth(40);
            employeeTable.getColumnModel().getColumn(4).setMinWidth(35);
            employeeTable.getColumnModel().getColumn(4).setPreferredWidth(65);
            employeeTable.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusLabel.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 51, 51));
        statusLabel.setText("Status");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        editEmployeeDialog.pack();
        editEmployeeDialog.setLocationRelativeTo(this);
        editEmployeeDialog.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteEmployeeDialog.pack();
        deleteEmployeeDialog.setLocationRelativeTo(this);
        deleteEmployeeDialog.setVisible(true);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        newEmployeeDialog.pack();
        newEmployeeDialog.setLocationRelativeTo(this);
        newEmployeeDialog.setVisible(true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void newDialogCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDialogCancelButtonActionPerformed
        newEmployeeDialog.dispose();
    }//GEN-LAST:event_newDialogCancelButtonActionPerformed

    private void editDialogCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDialogCancelButtonActionPerformed
        editEmployeeDialog.dispose();
    }//GEN-LAST:event_editDialogCancelButtonActionPerformed

    private void deleteDialogCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDialogCancelButtonActionPerformed
        deleteEmployeeDialog.dispose();
    }//GEN-LAST:event_deleteDialogCancelButtonActionPerformed

    private void allEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allEmployeesButtonActionPerformed
        olderThanValue.setEnabled(false);
        youngerThanValue.setEnabled(false);
        salaryHigherValue.setEnabled(false);
        salaryLowerValue.setEnabled(false);
    }//GEN-LAST:event_allEmployeesButtonActionPerformed

    private void olderThanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olderThanButtonActionPerformed
        olderThanValue.setEnabled(true);
        youngerThanValue.setEnabled(false);
        salaryHigherValue.setEnabled(false);
        salaryLowerValue.setEnabled(false);
    }//GEN-LAST:event_olderThanButtonActionPerformed

    private void youngerThanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youngerThanButtonActionPerformed
        olderThanValue.setEnabled(false);
        youngerThanValue.setEnabled(true);
        salaryHigherValue.setEnabled(false);
        salaryLowerValue.setEnabled(false);
    }//GEN-LAST:event_youngerThanButtonActionPerformed

    private void salaryHigherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryHigherButtonActionPerformed
        olderThanValue.setEnabled(false);
        youngerThanValue.setEnabled(false);
        salaryHigherValue.setEnabled(true);
        salaryLowerValue.setEnabled(false);
    }//GEN-LAST:event_salaryHigherButtonActionPerformed

    private void salaryLowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryLowerButtonActionPerformed
        olderThanValue.setEnabled(false);
        youngerThanValue.setEnabled(false);
        salaryHigherValue.setEnabled(false);
        salaryLowerValue.setEnabled(true);
    }//GEN-LAST:event_salaryLowerButtonActionPerformed

    private void newDialogSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDialogSaveButtonActionPerformed
        if (newNameValue.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Name can`t be empty!");
        } else if (newAgeValue.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Age can`t be empty!");
        } else if (newAddressValue.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Address can`t be empty!");
        } else if (newSalaryValue.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Salary can`t be empty!");
        } else {

            Session session = HibernateUtil.createSessionFactory().openSession();
            Transaction tx = null;
            Employee employee = new Employee(newNameValue.getText(), Integer.parseInt(newAgeValue.getText()), newAddressValue.getText(), Double.parseDouble(newSalaryValue.getText()));

            try {
                tx = session.beginTransaction();
                session.persist(employee);
                tx.commit();
                JOptionPane.showMessageDialog(null, "New employee saved successfully!");
                newEmployeeDialog.dispose();
                statusLabel.setText("New employee saved successfully!");

            } catch (HibernateException ex) {
                if (tx != null) {
                    tx.rollback();
                    statusLabel.setText(ex.getMessage());
                }
            } finally {
                HibernateUtil.close();
            }
        }
    }//GEN-LAST:event_newDialogSaveButtonActionPerformed

    private void editDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDialogButtonActionPerformed
        if (editIDValue.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Employee ID can`t be null!");
        } else {

            Session session = HibernateUtil.createSessionFactory().openSession();
            Transaction tx = null;

            try {

                tx = session.beginTransaction();

                Employee employee = (Employee) session.get(Employee.class, Integer.parseInt(editIDValue.getText()));

                if (!(editNameValue.getText().equals(""))) {
                    employee.setName(editNameValue.getText());
                }
                if (!(editAgeValue.getText().equals(""))) {
                    employee.setAge(Integer.parseInt(editAgeValue.getText()));
                }
                if (!(editAddressValue.getText().equals(""))) {
                    employee.setAddress(editAddressValue.getText());
                }
                if (!(editSalaryValue.getText().equals(""))) {
                    employee.setSalary(Double.parseDouble(editSalaryValue.getText()));
                }

                session.update(employee);
                tx.commit();
                JOptionPane.showMessageDialog(null, "Changes saved successfully!");
                editEmployeeDialog.dispose();
                statusLabel.setText("Changes saved successfully!");
            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
                statusLabel.setText(e.getMessage());
            } finally {
                HibernateUtil.close();
            }

        }
    }//GEN-LAST:event_editDialogButtonActionPerformed

    private void deleteDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDialogButtonActionPerformed
        if (deleteIDValue.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Employee ID can`t be null");
        } else {

            Session session = HibernateUtil.createSessionFactory().openSession();
            Transaction tx = null;

            try {
                tx = session.beginTransaction();
                Employee employee = (Employee) session.get(Employee.class, Integer.parseInt(editIDValue.getText()));
                session.delete(employee);
                tx.commit();
                JOptionPane.showMessageDialog(null, "Employee deleted successfully!");
                deleteEmployeeDialog.dispose();
                statusLabel.setText("Employee deleted successfully!");

            } catch (HibernateException e) {
                if (tx != null) {
                    tx.rollback();
                }
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
                statusLabel.setText(e.getMessage());
            } finally {
                HibernateUtil.close();
            }

        }
    }//GEN-LAST:event_deleteDialogButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();

        Session session = HibernateUtil.createSessionFactory().openSession();
        Transaction tx = null;

        String hql = "from Employee";

        Query query = session.createQuery(hql);
        List<Employee> employees = null;

        try {

            tx = session.beginTransaction();

            employees = query.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            statusLabel.setText(e.getMessage());
        } finally {
            HibernateUtil.close();
        }

        for (int i = 0; i < employees.size(); i++) {
            int data1 = employees.get(i).getId();
            String data2 = employees.get(i).getName();
            int data3 = employees.get(i).getAge();
            String data4 = employees.get(i).getAddress();
            double data5 = employees.get(i).getSalary();

            Object[] row = {data1, data2, data3, data4, data5};
            model.addRow(row);
        }
        statusLabel.setText("Employees loaded");

    }//GEN-LAST:event_formWindowOpened

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        model.setRowCount(0);

        Session session = HibernateUtil.createSessionFactory().openSession();
        Transaction tx = null;

        String allEmployeesHQL = "from Employee";
        String olderThanHQL = "from Employee as employee where employee.age >" + olderThanValue.getText();
        String youngerThanHQL = "from Employee as employee where employee.age <" + youngerThanValue.getText();
        String salaryHigherHQL = "from Employee as emloyee where emloyee.salary >" + salaryHigherValue.getText();
        String salaryLowerHQL = "from Employee as employee where employee.salary <" + salaryLowerValue.getText();
        List<Employee> employees = null;
        Query query = null;

        if (allEmployeesButton.isSelected()) {
            query = session.createQuery(allEmployeesHQL);
            statusLabel.setText("Showing all employees");
        } else if (olderThanButton.isSelected()) {
            query = session.createQuery(olderThanHQL);
            statusLabel.setText("Showing employees older than " + olderThanValue.getText());
        } else if (youngerThanButton.isSelected()) {
            query = session.createQuery(youngerThanHQL);
            statusLabel.setText("Showing employees younger than " + youngerThanValue.getText());
        } else if (salaryHigherButton.isSelected()) {
            query = session.createQuery(salaryHigherHQL);
            statusLabel.setText("Showing employees with salary higher than " + salaryHigherValue.getText());
        } else if (salaryLowerButton.isSelected()) {
            query = session.createQuery(salaryLowerHQL);
            statusLabel.setText("Showing employees with salary lower than " + salaryLowerValue.getText());
        }

        try {

            tx = session.beginTransaction();

            employees = query.list();

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            statusLabel.setText(e.getMessage());
        } finally {
            HibernateUtil.close();
        }
        for (int i = 0; i < employees.size(); i++) {
            int data1 = employees.get(i).getId();
            String data2 = employees.get(i).getName();
            int data3 = employees.get(i).getAge();
            String data4 = employees.get(i).getAddress();
            double data5 = employees.get(i).getSalary();

            Object[] row = {data1, data2, data3, data4, data5};
            model.addRow(row);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allEmployeesButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteDialogButton;
    private javax.swing.JButton deleteDialogCancelButton;
    private javax.swing.JDialog deleteEmployeeDialog;
    private javax.swing.JTextField deleteIDValue;
    private javax.swing.JTextField editAddressValue;
    private javax.swing.JTextField editAgeValue;
    private javax.swing.JButton editButton;
    private javax.swing.JButton editDialogButton;
    private javax.swing.JButton editDialogCancelButton;
    private javax.swing.JDialog editEmployeeDialog;
    private javax.swing.JTextField editIDValue;
    private javax.swing.JTextField editNameValue;
    private javax.swing.JPanel editPanel;
    private javax.swing.JTextField editSalaryValue;
    private javax.swing.JTable employeeTable;
    private javax.swing.ButtonGroup filterButtonGroup;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField newAddressValue;
    private javax.swing.JTextField newAgeValue;
    private javax.swing.JButton newButton;
    private javax.swing.JButton newDialogCancelButton;
    private javax.swing.JButton newDialogSaveButton;
    private javax.swing.JDialog newEmployeeDialog;
    private javax.swing.JTextField newNameValue;
    private javax.swing.JTextField newSalaryValue;
    private javax.swing.JRadioButton olderThanButton;
    private javax.swing.JTextField olderThanValue;
    private javax.swing.JButton refreshButton;
    private javax.swing.JRadioButton salaryHigherButton;
    private javax.swing.JTextField salaryHigherValue;
    private javax.swing.JRadioButton salaryLowerButton;
    private javax.swing.JTextField salaryLowerValue;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JRadioButton youngerThanButton;
    private javax.swing.JTextField youngerThanValue;
    // End of variables declaration//GEN-END:variables

}
